### ISSUE TITLE
Support Index multiEntry

### ISSUE THREAD

**Issue by pixelcort** [indexeddbshim/IndexedDBShim#16]
http://www.w3.org/TR/IndexedDB/#dfn-multientry

Might require moving away from column-based indexes.

**Comment by axemclion** [comment]
The way webkit and Firefox implement this is have a separate table (instead of a column in the same table) to support multi-entry flags. 
However, that basically means that you select from one table, and then select from another. I wanted to see if I can do this so that I can support this only for multi-entry indexes, and leave the normal indexes as they are implemented now.

**Comment by mvayngrib** [comment]
Maybe you can store a multivalue value like ["a", "b", "c", "d"] as ",a,b,c,d," and then when querying for "b" for example, use 

```
LIKE %,b,%
```

**Comment by axemclion** [comment]
@mvayngrib That is actually a good idea. I can always store them as JSON.stringify([key1, key2, complexObjectKey3]) - that should helpfully work.

**Comment by CaryLorrk** [comment]
Is there any schedule for multiEntry support?

**Comment by JamesMessinger** [comment]
Good news!   IndexedDBShim now supports multi-entry indexes.   Give it a try with the latest version and let us know if you find any problems.  Thanks!
