### ISSUE TITLE
Problems with WorxWeb 10.0

### ISSUE THREAD

**Issue by jeanpaulnet** [indexeddbshim/IndexedDBShim#182]
We are using IndexedDBShim on WorxWeb 10.0 browser in IOS.

The WorxWeb does not supports IndexedDb as it is using UIWebView instead of Safari-WKWebView.
But, WorxWeb supports WebSQL.

The problem is, the shim is not supporting WebSQL too.

We are calling window.indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB;

and it is returning false!

Any solutions?

**Comment by JamesMessinger** [comment]
This is due to a bug in WebKit (see [here](https://bugs.webkit.org/show_bug.cgi?id=137034)).  The `window.indexedDB` variable is read-only, so we can't shim it.   Until WebKit fixes the bug, there are two possible workarounds that you can use:
1. Use `window.shimIndexedDB` instead of `window.indexedDB`
   We _always_ add this property to the window object, even if the browser natively supports IndexedDB.  This allows you to use the shim instead of the native implementation, which is useful because some native implementations are really buggy (Safari and IE).
2. Create an `indexedDB` variable in your closure
   By creating a variable named `indexedDB`, all the code within that closure will use the variable instead of the `window.indexedDB` property.  For example:

``` javascript
(function() {
    // This works on all browsers, and only uses IndexedDBShim as a final fallback 
    var indexedDB = window.indexedDB || 
                    window.mozIndexedDB ||
                    window.webkitIndexedDB || 
                    window.msIndexedDB || 
                    window.shimIndexedDB;

    // This code will use the native IndexedDB, if it exists, or the shim
    indexedDB.open("MyDatabase", 1);
})();
```

**Comment by jeanpaulnet** [comment]
Thanks a lot BigstickCarpet, the second option worked for us.
