### ISSUE TITLE
IndexedDB not working on chrome after applying IndexedDBShim

### ISSUE THREAD

**Issue by AbuSufyan** [indexeddbshim/IndexedDBShim#192]
Hi,
We are using indexedDB for data storage, its working fine on all compatible browsers, than we find IndexedDBShim and I click on Live Demo with following URL
http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=True
when it is completed i run the application, its strange my IndexedDB not return any object, than i revert back to native browser by using following URL
http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=False
by doing this, when we run the application a message is appeared your browser is not compatible for IndexedDB. Can you find the route cause of this problem and fixed it?
How i roll back these changes to my default settings, so our application is properly run on chrome like before applying IndexedDBShim?
Please note that i was reset the default setting of chrome and also update its latest version but the problem still exists.
Thanks in advance

**Comment by JamesMessinger** [comment]
Thanks for submitting this bug report, but I'm not sure I understand what the problem is.   Are you saying that once you've browsed to a page that uses the shim (such as http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true), any other page you browse to after that is unable to use IndexedDB? 

Here's a test:
1. Browse to [this page](http://run.plnkr.co/plunks/6NaDSpuy2aFrehhZv0NY/) to verify that your browser's _native_ IndexedDB is working
2. Browse to [this page](http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true), which uses the IndexedDBShim
3. Browse back to [this page](http://run.plnkr.co/plunks/6NaDSpuy2aFrehhZv0NY/) to verify that your browser's _native_ IndexedDB is _still_ working

**Comment by AbuSufyan** [comment]
Thanks for your quick response, yes after browsed above page i was unable to use IndexedDB.

**Comment by JamesMessinger** [comment]
What version of Chrome are you using?  And on what operating system?   I've tried it using Chrome 42 on Mac and Windows, and it works for me. 

I suspect that you're doing something different than I am, since it's not possible for a script to modify the DOM in such a way that it affects subsequent pages.   As soon as the browser navigates to a new page, the DOM is completely re-created, which means any changes made by IndexedDBShim are no longer present.

**Comment by AbuSufyan** [comment]
My chrome version is 42.0.2311.90, operating system windows 7 professional. Can you first visit http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=True
When it is 100 % complete, try to open indexedDB objects, than revert back to native browser 
http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=False
and again try to access objects. This is my complete steps that i was done, after that my indexedDB not worked.

**Comment by JamesMessinger** [comment]
What do you mean by "When it is 100% complete, try to open indexedDB objects"?   Do you mean "When it is 100% complete, try to go to a page that opens indexedDB objects"?   Because that's what [this page](http://run.plnkr.co/plunks/6NaDSpuy2aFrehhZv0NY/) does

**Comment by AbuSufyan** [comment]
I mean when testing is complete 100%, its take time for completion with some failures when it is complete than read data from indexedDB, from this stage i was not retrieved data from indexedDB than i was revert back but still i was not get saved data.

**Comment by JamesMessinger** [comment]
I'm still not sure I understand the problem.   There is no "revert back" functionality, and there's no need for you to browse to http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true or http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=false in your code.  That's not how polyfills work.   Here's the way things should work:
1. You add the polyfill to your page via a `<script>` tag.  This comes _before_ any `<script>` tags for your own code.
2. The polyfill will detect whether the browser supports IndexedDB or not.  If it does, then the polyfill does nothing.  If the browser DOES NOT support IndexedDB and DOES support WebSQL, then the polyfill adds IndexedDB support.
3. Add your code that relies on IndexedDB to the page via `<script>` tags.  These tags must come _after_ the IndexedDBShim `<script>` tag.
4. Your code will run the same, regardless of whether IndexedDB is natively supported by the browser or if the polyfill added it.

**Comment by AbuSufyan** [comment]
Thank you so much, I solved my problem, and now IndexedDB is working fine on chrome.
