### ISSUE TITLE
11 Tests failing on Windows 8.1

### ISSUE THREAD

**Issue by bvahdat** [indexeddbshim/IndexedDBShim#198]
Hi

I'm trying to get IndexedDBShim working inside a App on Windows 8.1 (Apache Cordova 5.0.0). After running the [tests](https://github.com/axemclion/IndexedDBShim/tree/master/tests) on Windows (using a dummy app created on Windows 8.1 as described [here](https://cordova.apache.org/docs/en/5.0.0/guide_cli_index.md.html#The%20Command-Line%20Interface)) I noticed that among others the IDBIndex related tests are failing:

![cordova-5 0 0-shimindexeddb](https://cloud.githubusercontent.com/assets/3122177/7553922/9a9fe3a8-f710-11e4-89f2-1044297150bf.jpg)

For now I don't create Indexes and that resolves the problem temporarily for me. Looking at #178 it seems like Hybrid-Cordova based Apps on Windows 8.1 is not in scope to be tested (please correct me if I'm wrong). However Windows Phone 8.1 seems to be in the scope. 

Side note: To my understanding for running the tests on Windows 8.1 there'e no need for WebSQL to be installed as a Cordova plugin but only on Windows Phone, but again please correct me if I'm wrong. 

Last but not least thanks for all this awesome work you guys are doing. Keep it up! :+1:

**Comment by JamesMessinger** [comment]
Are you using a Cordova plug-in, or are you using IndexedDBShim directly?   If you're using a Cordova plug-in, then which one?  There are two: [cordova-plugin-indexeddb](https://github.com/MSOpenTech/cordova-plugin-indexedDB) and [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async)

Also, are you certain that you're actually running on Windows 8.1 and not Windows 8.0?  When you add the `windows` or `windows8` platforms via Cordova, it actually adds three projects: for Windows 8.0, Windows 8.1, and Windows Phone 8.1.   By default, the Windows 8.0 project is the startup project, which means that it's the project that gets run when you run any of the Cordova CLI commands (such as `cordova run windows` or `cordova emulate windows`).   To run on Windows 8.1, you'll need to open the solution in Visual Studio and change the startup project.

I just now tested it by creating a new Cordova app and adding the `windows` platform.  I then ran the following combinations:
- Windows 8.0 with the `cordova-plugin-indexeddb` plugin :+1: 
- Windows 8.1 with the `cordova-plugin-indexeddb` plugin :+1: 
- Windows 8.0 with the `cordova-plugin-indexeddb-async` plugin :-1: 
- Windows 8.1 with the `cordova-plugin-indexeddb-async` plugin :+1: 

In three of the four cases, all unit tests passed successfully.   The only exception was Windows 8.0 with the `cordova-plugin-indexeddb-async` plugin, in which case the first 11 tests failed.  But this is due to a bug in the tests (which I will fix shortly), not in the actual IndexedDBShim.  Other than those 11 tests, all other tests pass fine, including all tests related to indexes.

**Comment by JamesMessinger** [comment]
I just released version 2.0.2 of `IndexedDBShim` and `cordova-plugin-indexeddb-async`.  Those first 11 unit tests have been fixed to work on Windows 8.0.   I've tested and verified that now all unit tests pass on all four of the following combinations:
- Windows 8.0 with the `cordova-plugin-indexeddb` plugin :+1: 
- Windows 8.1 with the `cordova-plugin-indexeddb` plugin :+1: 
- Windows 8.0 with the `cordova-plugin-indexeddb-async` plugin :+1: 
- Windows 8.1 with the `cordova-plugin-indexeddb-async` plugin :+1:

**Comment by bvahdat** [comment]
Wow thanks for the quick turn around, now all tests are passing on Windows 8.1 WebView (both when using native MS indexedDB Impl as well as the IndexedDBShim itself), awesome! BTW I was aware of the step with Visual Studio upgrade.

One last question before you close this ticket.

I was/am using [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) and not [this](https://github.com/MSOpenTech/cordova-plugin-indexedDB) or [this](https://github.com/ABB-Austin/cordova-plugin-indexedDB) plugin. Do you think I'm on the right track if my _only_ target runtime is Windows 8.1?

**Comment by JamesMessinger** [comment]
If your only target is Windows 8.1, then you don't actually need any of the Cordova plugins, and you may not need IndexedDBShim at all.   

The main reason to use the Cordova plugins is that they work across multiple platforms.  On some platforms (like Windows Phone), they do a _lot_ of polyfilling.  On other platforms (like Windows 8.0 and 8.1), they don't do anything at all.   So, if you're only targeting Windows 8.1, then the plugin isn't actually doing anything for you.

That said, even though Windows 8.0 and 8.1 both support IndexedDB natively, they're missing a few features - such as multi-entry indexes and compound keys.  If you don't need those features, then you can just use the native IndexedDB implementation.  No shim or plugins needed at all.  But if you _do_ want to use compound keys in your app, then IndexedDBShim can polyfill that for you.  This is an opt-in feature though.  You need to call `shimIndexedDB.__useShim()`.

**Comment by bvahdat** [comment]
Don't really get it yet! AFAIK [WebSql](http://caniuse.com/#search=websql) is supported neither through IE 11 nor Windows 8.1 WebView, right? So if I want to _force_ making use of IndexedDBShim in my App through the `shimIndexedDB.__useShim()` API how does IndexedDBShim is expected to work on IE 11 or Windows 8.1?

Also what it says [here](http://nparashuram.com/IndexedDBShim/) confuses me a bit:

> This shim is basically an IndexedDB-WebSql adapter.

As because if WebSql is not available on a given runtime then how should IndexedDBShim kick in and work properly?

**Comment by DickvdBrink** [comment]
Windows 8.1 app in cordova doesnt support IndexedDb from local urls and doesn't support WebSql either.
If you install [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) it uses https://github.com/Thinkwise/cordova-plugin-websql to enable WebSql so the shim can work.

If you target it as a website for Windows 8.1 you don't need to use the shim because IndexedDb works in that case.

Does this answer your question?

**Comment by bvahdat** [comment]
Still more confused than before, so please let me recapitulate:

The App I'm working on runs both on IE 11 as well as Windows 8.1 WebView (Apache Cordova) with whatever native IndexedDB implementation these software come with. Well there’re some issues like [this one](https://github.com/bramski/angular-indexedDB/issues/32) I’m currently running into but in general the App works so far. So don't really get the point when you say:

> Windows 8.1 app in cordova doesnt support IndexedDb from local urls and doesn't support WebSql either.

Regarding:

> If you install cordova-plugin-indexeddb-async it uses https://github.com/Thinkwise/cordova-plugin-websql to enable WebSql so the shim can work.

I guess the WebSql thingy with [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) comes into play only when on Windows Phone, see [here](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async/blob/master/www/requireWebSql.js#L1). Feel free to correct me if I'm wrong.

So again my question: assuming I would use [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) which would leverage the shiny and lovely `IndexedDBShim v2.0.2` for me, example on Windows 8.1 WebView, then how does it really work if there's no WebSql thingy there @ runtime? Do you get my point?

**Comment by DickvdBrink** [comment]
Ai, My bad I meant Windows Phone on 8.1 doesn't support indexedDB from local urls. Sorry about the confusion.

> I guess the WebSql thingy with cordova-plugin-indexeddb-async comes into play only when on Windows Phone, see here. Feel free to correct me if I'm wrong.

Correct.

> So again my question: assuming I would use cordova-plugin-indexeddb-async which would leverage the shiny and lovely  IndexedDBShim v2.0.2  for me, example on Windows 8.1 WebView, then how does it really work if there's no WebSql thingy there @ runtime? Do you get my point?

Ah now I understand what you mean, `cordova-plugin-indexeddb-async` also installs `cordova-plugin-websql` for windows phone and does this by modifying the solution (for Windows Phone only) so @BigstickCarpet was correct by saying that for Windows 8.1 you don't need to install the plugin as it doesn't do anything. So on windows 8.1 without a WebSql plugin (so `window.openDatabase` exists) the shim can't work because there is no WebSql so I guess your last part is also correct.
Sorry about the confusion!

**Comment by JamesMessinger** [comment]
@bvahdat - Sorry for all the confusion.  Hopefully I can clear it up.

#### Windows _Phone_ 8.1
- **native**
  Does _not_ support IndexedDB and does _not_ support WebSQL.
- **w/ `IndexedDBShim` (no Cordova plugins)**
  Does _not_ work, since neither IndexedDB nor WebSQL is supported
- **w/ `cordova-plugin-indexeddb`**
  Supports IndexedDB and WebSql automatically.  No need to call `shimIndexedDB.__useShim()`.
- **w/ `cordova-plugin-indexeddb-async`**
  Supports IndexedDB and WebSql automatically.  No need to call `shimIndexedDB.__useShim()`.

#### IE 10 or 11 (_not_ a Cordova app)
- **native**
  Supports IndexedDB, but does _not_ support WebSQL.
- **w/ `IndexedDBShim`**
  `shimIndexedDB.__useShim()` can be called to add compound key support to the browser's _native_ IndexedDB.  It does _not_ use or require WebSQL.

#### Windows 8.0 or 8.1 Cordova app
- **native**
  Supports IndexedDB, but does _not_ support WebSQL.
- **w/ `IndexedDBShim`**
  `shimIndexedDB.__useShim()` can be called to add compound key support to the browser's _native_ IndexedDB.  It does _not_ use or require WebSQL.
- **w/ `cordova-plugin-indexeddb`**
  The _synchronous_ WebSQL plugin is loaded, which adds WebSQL support.  By default, IndexedDBShim won't do anything, since IndexedDB is already natively supported.  Calling `shimIndexedDB.__useShim()` will completely replace the device's native IndexedDB implementation with the WebSQL adapter, which will use the _synchronous_ WebSQL plugin.
- **w/ `cordova-plugin-indexeddb-async`**
  The WebSQL plugin is _not_ loaded.  By default, IndexedDBShim won't do anything, since IndexedDB is already natively supported.  Calling `shimIndexedDB.__useShim()` will add compound key support to the browser's _native_ IndexedDB.  It does _not_ use or require WebSQL.

**Comment by DickvdBrink** [comment]
> So again my question: assuming I would use cordova-plugin-indexeddb-async which would leverage the shiny and lovely IndexedDBShim v2.0.2 for me, example on Windows 8.1 WebView, then how does it really work if there's no WebSql thingy there @ runtime? Do you get my point

To answer the last part: 
https://github.com/axemclion/IndexedDBShim/blob/master/src/polyfill.js

Didnt even know we did this lol, it is kinda new I guess but it adds missing stuff to IE.

**Comment by bvahdat** [comment]
@BigstickCarpet 

> IE 10 or 11 (not a Cordova app)
> 
> native
> Supports IndexedDB, but does not support WebSQL.
> 
> w/ IndexedDBShim
> shimIndexedDB.__useShim() can be called to add compound key support to the browser's native IndexedDB. It does not use or require WebSQL.

Given [the full WebSQL support on Chrome compared to IE 11](http://caniuse.com/#search=websql) when I run the [tests](https://github.com/axemclion/IndexedDBShim/blob/master/test/index.html) this's what I'm observing.

## Chrome `42.0.2311.152 m` on Windows 8.1

![shimindexeddb-chrome](https://cloud.githubusercontent.com/assets/3122177/7628709/da1f43ca-fa26-11e4-8f1c-bd1970c429f8.jpg)

## IE 11 on Windows 8.1

![shimindexeddb-ie11](https://cloud.githubusercontent.com/assets/3122177/7628711/dcd256e8-fa26-11e4-8209-e2a5f5cc2e64.jpg)

On IE 11 `qunit` seems to be frozen, do you maybe know why?

**Comment by bvahdat** [comment]
O.K. I've got the tests running now on IE 11 as well. The reason was because IE refuses to run the tests when reading `index.html` from the local file system. I started a [http server](https://www.npmjs.com/package/http-server) for this purpose:

![http-server](https://cloud.githubusercontent.com/assets/3122177/7629100/47cf8b02-fa2a-11e4-865f-5288b2fc2675.jpg)

And came a bit further with 7 tests failing on IE 11 / Windows 8.1. On Chrome however it's all good!

![shimindexeddb-ie11-http](https://cloud.githubusercontent.com/assets/3122177/7629102/4cb93438-fa2a-11e4-9ccd-92196b33a98a.jpg)

**Comment by JamesMessinger** [comment]
Hi.  I've been away on vacation for a couple weeks, so I'm just now catching up on things.  Is this issue resolved now?  Or is there still a problem?

**Comment by bvahdat** [comment]
> Am 27.05.2015 um 17:04 schrieb James Messinger notifications@github.com:

Hi

Yes please see my previous comment about the failing tests on IE 11

**Comment by JamesMessinger** [comment]
Ah, ok.  Sorry for the confusion.  When you browse to the `/test` folder, you're running the QUnit tests, which don't work on IE.  Those tests were written before IndexedDBShim supported IE. 

When you browse to the `/tests` folder (notice the extra "s"), you're running the Mocha tests, which _do_ support IE.

**Comment by bvahdat** [comment]
> Those tests were written before IndexedDBShim supported IE

I see, but maybe a better approach would be to skip those tests if `navigator.userAgent` contains `IE xyz` and whatnot?

Anyway I guess this issue can be closed now. And many thanks for all your support!

**Comment by JamesMessinger** [comment]
Glad to help.   If I get a chance, I'll add a `userAgent` check to those tests, to prevent future confusion.
