### ISSUE TITLE
Avoid using DOMError

### ISSUE THREAD

**Issue by foolip** [indexeddbshim/IndexedDBShim#209]
`DOMError` is used in a few places in IndexedDBShim. DOMError has been removed from the spec and may be removed from Chrome:
https://code.google.com/p/chromium/issues/detail?id=460725

The only problematic bit of real code I can see is in `createNativeDOMError` but fortunately that doesn't seem to actually be used. Still, best to check in case DOMError does end up being removed from browsers.

**Comment by DickvdBrink** [comment]
Not sure if we can because we also have older browsers for example older android/ios versions

The code does seem to fallback gracefully according to this code
https://github.com/axemclion/IndexedDBShim/blob/89ce0046adebf540cb38682f9604550e4c53bb4f/dist/indexeddbshim.js#L1403-L1440

Is this good enough?

**Comment by foolip** [comment]
Ah, I see, I saw `test` and though I was looking at testing code. Yes, it sure looks like your code would survive the removal of DOMError, so no problem.

**Comment by DickvdBrink** [comment]
Thanks for reporting it though :)

**Comment by foolip** [comment]
No problem! I found this by searching for DOMError in httparchive.org data, so your shim is used out there in the wild :)
