### ISSUE TITLE
Null index key causes error

### ISSUE THREAD

**Issue by JamesMessinger** [indexeddbshim/IndexedDBShim#215]
If an object store has an index, and a record is added with a `null` value in the index field, an error is thrown.  For example:

``` javascript
objectStore.add({keyField: "foo", indexField: "bar"});  // Works fine
objectStore.add({keyField: "biz", indexField: null});   // Error!!!
```

Need to check the spec and existing browser implementations to see what the correct behavior is.  If it turns out that this _should_ throw an error, then we need to throw the _correct_ error.  Currently, the error is _"Cannot read property 'encode' of undefined"_, which is clearly not right.

Here's a [live demo of the problem](http://www.dementedplayground.com/Dexie.js-master/samples/ajax-populate/populateFromAjaxCall_with_shim.html), as submitted by @isaacbdawson in Issue #214.  It's not just a Safari bug (I reproduced it in Chrome), and it's not a bug with Dexie.  The error happens on [line #438 of `Key.js`](https://github.com/axemclion/IndexedDBShim/blob/28cf794b8a3c097f94497c1ea341dca4cfe81acb/src/Key.js#L438)

**Comment by apankov** [comment]
Hi, just wanted to make sure you guys got my comment at https://github.com/axemclion/IndexedDBShim/issues/214#issuecomment-142646810

**Comment by open-environment** [comment]
Wanted to point out that you will also get this error if you attempt to define a boolean field as true or false (which works in IndexedDB but not WebSQL) as opposed to 0 or 1.

**Comment by brettz9** [comment]
I believe the `null` issue may be fixed now.

For the case of booleans, using `master`, you might try changing:

``` js
const collations = ['undefined', 'number', 'date', 'string', 'array', 'object'];
```

to:

``` js
const collations = ['undefined', 'number', 'date', 'string', 'array', 'object', 'boolean'];
```

and adding to `types`:

```
    boolean: {
        encode: function (key) {
            return collations.indexOf('boolean') + '-' + key;
        },
        decode: function (key) {
            return Boolean(key.slice(2));
        }
    },
```

and changing:

``` js
} else if (!types[type] || type === 'object' || (type !== 'string' && isNaN(key))) {
```

to:

``` js
} else if (!types[type] || type === 'object' || type === 'boolean' || (type !== 'string' && isNaN(key))) {
```

I can investigate this myself after my current focus may be done, but wanted to share in case it may help you now.

**Comment by brettz9** [comment]
I've added the code, but we need tests to confirm.

**Comment by brettz9** [comment]
Ok, sorry, it was premature for me to add the code.

Key validation indeed should not allow `null`, booleans, or objects, since the [recommendation](https://www.w3.org/TR/IndexedDB/#dfn-key) and [draft spec](http://w3c.github.io/IndexedDB/#key) both prohibit them as keys (unless the object is a date, array or ArrayBuffer, the latter not yet being supported).

However, the problem had been that we were not throwing as a proper DOMException when encountering bad keys (i.e., we were not always validating before attempting encoding) or we were not catching and silently ignoring when the bad key exception should have been caught internally, like when an insert is going to be made but indexes whose index keys are invalid will be ignored (i. e., [step 2 here](http://w3c.github.io/IndexedDB/#ref-for-index-referenced-9)).

I have fixed and tested for both of these scenarios in `master`so please pull again if you've already updated.

Although you should now get the proper error or silent ignoring in some cases, remember that, as with an object store keyPath, an index, in referencing a keyPath, should generally point to a valid key, which does not allow `null`, booleans, objects, etc.
