### ISSUE TITLE
Improve getting started sample code

### ISSUE THREAD

**Issue by emertechie** [indexeddbshim/IndexedDBShim#216]
Hi,

Great library but it took me a while to figure out exactly how to set it up correctly. From scanning the front page docs, there are only a couple of relevant code sections:

```
"To force IndexedDBShim to shim the browser's native IndexedDB, add this line to your script:"
window.shimIndexedDB.__useShim()
```

and:

```
// This works on all browsers, and only uses IndexedDBShim as a final fallback 
var indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;
```

The first one forces the shim (i.e. uses Web SQL DB) when you might have a perfectly good IndexedDB implementation already (in Chrome for example).

The second one won't work for Safari, as you can't replace `window.indexedDB`, so you'll always pick up the 'bad' version first.

I eventually ended up with code like this:

``` js
function getIndexedDB() {

    var isSafari = navigator.userAgent.indexOf('Safari') != -1 &&
        navigator.userAgent.indexOf('Chrome') == -1 &&
        navigator.userAgent.indexOf('Android') == -1;

    var isIE = !!window.msIndexedDB;

    var forceShim = isSafari || isIE;

    if (forceShim) {
        window.shimIndexedDB.__useShim();
    }

    if (isSafari) {
        // can't replace window.indexedDB in Safari so always use shimIndexedDB
        return window.shimIndexedDB;
    } else {
        // Use window.indexedDB for other browsers as it might be a patched up version (for IE for example)
        return window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;
    }
}
```

Where I only force the shim for the known-bad implementations and try to use any 'good' `window.indexedDB` implementations otherwise. This now works for me across Safari, Firefox, Chrome and IE.

Is this what others are doing? If so, I think it would be good to add some similar sample sample code to the home page.

Would save others a fair bit of time I think (I had to go digging in the source code more than once to see what was going on)

Thanks

**Comment by axemclion** [comment]
I think this is a great point. Would be great if you can send in a pull request with your findings - I think that would be a good starting point.

**Comment by emertechie** [comment]
Made a quick attempt at it. Have a look and see what you think

**Comment by JamesMessinger** [comment]
This isn't really a quickstart.  It's more like "one common usage scenario".  That's not necessarily a bad thing, bug it might be worth acknowledging that there are many different usage scenarios, and this is just one of them.  Otherwise, this could cause confusion for people who have different needs.

The decision to specifically check for Safari and IE is subjective.  For some people, IE's native IndexedDB is perfectly fine, and they need to shim Firefox instead.  For some people, _none_ of the native implementations are acceptable because of inconsistencies between them, so they call `shimIndexedDB.__useShim()` for _all_ browsers.  Some other people _only_ want to shim IndexedDB if the browser doesn't have it at all, so they _never_ call `shimIndexedDB.__useShim()` and _never_ use `window.shimIndexedDB`.

Also, a minor correction: The paragraph above the code sample says "_it will always return a Web SQL shim_", but that's not correct.  For browsers without WebSQL (like IE) the _native_ IndexedDB implementation is returned, not a WebSQL shim.

**Comment by emertechie** [comment]
@BigstickCarpet Great points, thanks for the feedback. I've reworded things a little. Hope it's clearer now

**Comment by brettz9** [comment]
I think this can be closed now since detection occurs in `src/setGlobalVars.js`. Feel free to reopen or file a new issue if you'd like to see some other changes or documentation.
