### ISSUE TITLE
Shim seems to set autoincrement separate from primary key

### ISSUE THREAD

**Issue by bduff9** [indexeddbshim/IndexedDBShim#225]
I am running into an issue I just pinned down.  Basically, I have an autoincremented primary key called mrcID.  I also start my app by populating this field with values.  So, I might insert 20 rows, where the highest value that gets inserted is 527.  I would expect, and without the shim this happens, is for the next record inserted to have id 528.  Instead, with the shim, it has 21.  If I have a record with id 21, then this fails with a constraint error as it should.

Is there a way to force the shim to pick up my ID values, or am I out of luck with this shim?  If you'd like to see an example of this issue, look here:
http://m-powerdev.com:8888/mrcjava/mrcclasses/MOBILECRM/test.html

This demo works fine and inserts the records into the db, however if you type the following into the console, you will see the error I am referencing:
db = new Dexie('mrcDB'); db.open().then(function() { db.table('MOBILECRM_M00060s').add({}); });

I would appreciate any feedback you have as this critical to my app.  Thank you!

**Comment by JamesMessinger** [comment]
The IndexedDB spec doesn't specify details about how auto-incremented keys should be generated.  Specifically, it doesn't address how generated keys should be affected by manually-specified keys in the same object store.  As a result, each browser vendor has implemented this differently.  

For example, let's say that you manually add the following keys (in this order): `5`, `500`, `100`.  After adding those keys, you add a record _without_ a key, so the browser generates an auto-incremented key.  On some browsers, the auto-incremented key will be `1`. On others it will be `101`.  On others it will be `501`.

Safari is the worst offender.  Any time you manually specify a value for an auto-incremented key, Safari resets its internal key generator to zero, so the next auto-incremented key will _always_ be `1`, even if there's already a record with a key of `1`.   Obviously, this causes duplicate key constraint errors.

We do have [some](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBObjectStore/add-put-spec.js#L209) [tests](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBObjectStore/add-put-spec.js#L592) in our test suite for this behavior.  But due to the wide range of browser implementations, our tests are pretty loose.  For example [this line](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBObjectStore/add-put-spec.js#L613) doesn't know whether the key will be `2` or `3`, and [this line](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBObjectStore/add-put-spec.js#L615) doesn't know whether the key will be `3`, `5`, or `100`.

My recommendation is that you **don't ever** manually assign values to auto-incremented keys.  If you  need certain records in an object store to have certain key values, then manually assign the keys for _all_ records in that object store.  Only use auto-incremented keys when you don't rely on _any_ specific key values.

**Comment by bduff9** [comment]
I see what you are saying, however I don't fully agree with what you are saying.  Outside of anything else, the primary key holds the values and needs to be unique.  If you allow the key to be manually set, you should at the very least ensure that new ones are still unique.  Or, you should not allow the primary key to be manually set if autoincremented a la certain relational dbs like DB2.

I get that browser implementation is very wonky, but that's why I'm using the shim, as it says it can replace or enhance wonky implementations.  On the whole, I like the shim so I wanted to share something I found that I consider incorrect.

My personal preference would be you change your getNextAutoIncKey function to return a unique value, not just seq + 1.  Alternatively, it would make sense to reject/ignore manually set keys when autoincrement is turned on.  Either one of this seems more correct IMO than allowing the code to break as soon as I insert just 1 record with an ID of 2 and then try to insert one more without specifying an ID.

In any case, I do appreciate the response as I did change my code to manually calculate a unque ID every time since this is not currently working.  Thank you for your time.

**Comment by JamesMessinger** [comment]
Yeah, I agree that the current implementation in the shim isn't ideal.  The only way to fix it and still be compatible with the spec is to make the `getNextAutoIncKey` function verify the uniqueness of the key, which is totally do-able, but would have a performance impact.

**Comment by brettz9** [comment]
I haven't looked too closely at the comments here, but `master` now updates the `sqlite_sequence` auto-increment table if the user supplied a numeric key to `add()` or `put()` which is greater or equal to the "current number".

Also fixed is a bug which was using `LIKE` to check on auto-complete instead of `=` which could be a problem if there were a store name existing within another store name.

@bduff9 , if this would address your issue, could you confirm that this is working for you now?

**Comment by brettz9** [comment]
The spec does indicate how auto-generation should occur (see the section on "current number"). The code in `master` should have already fixed this issue but feel free to reopen if not.

**Comment by brettz9** [comment]
And just FYI, in our old W3C tests, there is a KeyGenerator.js file which is now passing one of its three tests, and the other two tests can't yet be run to see how we're doing there as we still need to add `preventDefault` support on which the tests are relying.
