### ISSUE TITLE
Shim favours websql over indexeddb

### ISSUE THREAD

**Issue by romski** [indexeddbshim/IndexedDBShim#226]
I have an angular application that currently uses indexedb via angular-indexeddb. I want to support IOS and I have forced use of the shim in angular-indexeddb as follows:

`indexedDB = window.shimIndexedDB || window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB;`

When running a basic test, I have observed that the shim has used WebSQL for both IOS and Chrome on the desktop - is this expected behaviour? 

My expectation was that you would use indexeddb (when available and not broken), then WebSQL, then LocalStorage.

**Comment by JamesMessinger** [comment]
Sorry for taking so long to reply.  I've been away on holiday for a few weeks.

In your code sample, `window.shimIndexedDB` should come _last_, not first.  By putting it first, you're overriding the polyfill behavior and choosing to _always_ use the shim (WebSQL) instead of the default browser implementation. 

See the [Known Issues &mdash; iOS](https://github.com/axemclion/IndexedDBShim#ios) for a full explanation and code sample.

**Comment by romski** [comment]
Thank you for the reply. The shim is using WebSQL, which makes sense. 

I originally tried following the example and placing the shim at the end, but was getting an error when using the iphone. Specifically, an error was thrown when opening 2 databases at the same time. That said, it's been a couple of weeks, so I will try again and let you know the result.

**Comment by JamesMessinger** [comment]
ok.  Try it again and let us know if you find a problem.  We have [lots of unit tests](http://nparashuram.com/IndexedDBShim/tests/index.html) to ensure that it works on iOS.  But now that you mention it, our [`IDBFactory.open` tests](http://nparashuram.com/IndexedDBShim/tests/index.html?grep=IDBFactory.open) **don't** include a test to ensure that multiple databases can be opened simultaneously.  So maybe there's a bug there that we don't know about.
