### ISSUE TITLE
safari 9 incompatible

### ISSUE THREAD

**Issue by PedroJusto** [indexeddbshim/IndexedDBShim#227]
with safari 8 everithing was working, in safari 9 : "TypeError: undefined is not an object (evaluating 'indexedDB.open')"

**Comment by DickvdBrink** [comment]
Hmz, I tried this with a cordova application and everything worked there but that uses the webview.

I dont have access to an iPad with iOS 9 this week but will try to check it out

**Comment by PedroJusto** [comment]
can you try in safari 9 browser? I use your shim in a webworker and all works good until i updated safari to version 9.

since Web Workers don't have a window object, in my webworker I do "window= self;" and "importScripts('indexeddbshim.js')".

**Comment by open-environment** [comment]
i get the same error.

**Comment by mauron85** [comment]
same here. with cordova ios and ios 8.4.1

**Comment by brettz9** [comment]
There appears to be a problem with iOS9 and IndexedDB for non-Safari browsers. Our new code (discussed in #252) forces iOS9 non-Safari browsers to use the shim despite them supposedly having IndexedDB support. 

Until our next release, you can change your project's bower dependency line for "IndexedDBShim" to https://github.com/axemclion/IndexedDBShim#ios9 and run `bower install` in your project directory.

Closing for now but feel free to comment further or reopen if your issue is not resolved.

**Comment by brettz9** [comment]
Apologies, my last comment pertained to non-Safari iOS9 browsers. I have made a fix for the web workers issue, though not yet tested. Could someone report back on whether things are working now?

**Comment by brettz9** [comment]
Things are working fairly well on Desktop Safari 10 and Chrome, but I don't have Safari version 9 or iOS9 to test.

We have a new release candidate available for testing.

As I haven't heard back, I'll close now... A lot has changed since version 2 (including breaking changes affecting existing data) so best to file reports against the version 3.0.0 RC (currently RC-3).

**Comment by brettz9** [comment]
I might add that per https://github.com/axemclion/IndexedDBShim/issues/252#issuecomment-228707973 a more recent version (prior to a number of improvements though) was working fine with IOS9.
