### ISSUE TITLE
Range lower and upper bound hardcoded false

### ISSUE THREAD

**Issue by Abrissirba** [indexeddbshim/IndexedDBShim#235]
The following if statement exists in the begining of function IDBCursor. Why is the lower- and upperOpen hardcoded to false?

``` javascript
if (range !== undefined && !(range instanceof idbModules.IDBKeyRange)) {
    range = new idbModules.IDBKeyRange(range.lower, range.upper, false, false);
}
```

A better solution would be 

``` javascript
if (range !== undefined && !(range instanceof idbModules.IDBKeyRange)) {
    var lowerOpen = range.lowerOpen || false;
    var upperOpen = range.upperOpen || false;
    range = new idbModules.IDBKeyRange(range.lower, range.upper, lowerOpen, upperOpen);
}
```

**Comment by brettz9** [comment]
The code as it is now is:

``` js
    if (range !== undefined && !(range instanceof IDBKeyRange)) {
        range = new IDBKeyRange(range, range, false, false);
    }
```

I think this new code is there because, if some scalar key is provided (as opposed to a range), this code will default to behave effectively as `only(range)`.

What is your use case? Would you like to supply an object which is not an `IDBKeyRange` and prefer that we duck type in place of the `instanceof` check?

**Comment by brettz9** [comment]
We are now using duck-typing instead of `instanceof`, so I will close. Feel free to reopen or add a new issue if you have other concerns.
