### ISSUE TITLE
IDBCursor problems ios device 

### ISSUE THREAD

**Issue by yuber1792** [indexeddbshim/IndexedDBShim#245]
Hi ,I have problems using the IDBCursor:

  object.openCursor().onsuccess = function(event) {
              var cursor = event.target.result;

cursor returns null. only ios in android works correctly.

**Comment by brettz9** [comment]
Can you give the iOS version as well as a complete, but minimal, test case that causes the problem?

**Comment by brettz9** [comment]
There appears to be a problem with iOS9 and IndexedDB for non-Safari browsers. Our new code (discussed in #252) forces iOS9 non-Safari browsers to use the shim despite them supposedly having IndexedDB support. 

Until our next release, you can change your project's bower dependency line for "IndexedDBShim" to https://github.com/axemclion/IndexedDBShim#ios9 and run `bower install` in your project directory.

Closing for now but feel free to comment further or reopen if your issue is not resolved.
