### ISSUE TITLE
Recent changes break Safari 6 compatibility

### ISSUE THREAD

**Issue by RazorDE** [indexeddbshim/IndexedDBShim#261]
All commits since 19a076e are no longer compatible with MacOS Safari 6.1.6 (7537.78.2) and iOS 6.1.6 (10B500). Although it is still possible to create and store data in the websql-database it is no longer possible to retrieve it.

The following error is displayed in the current version (a90ff2a) of indexeddbshim.js when accessing the database using indexedDB.open:
Type Error: Attempted to assign to readonly property indexeddbshim.js:10260

The commit 9ca9910 is the last one where this issue doesn't occur.
I hope this information is adequate enough such that this problem can be reproduced and hopefully fixed.

**Comment by brettz9** [comment]
Thank you very much for the precise report. Apparently this was due to Safari interpreting the SQLite rows' `item`s properties as readonly. I addressed the particular error you reported in `master` by copying properties onto a new object.

I plan to take a look at the other Safari issues people have reported. FYI, most of https://github.com/axemclion/IndexedDBShim/labels/Bug-environment%20support relate to Safari, so it is possible some other Safari-related issues have already been reported.

But if you see any other unreported errors, please let me know. I will close this for now, though feel free to add new issues for any other errors you can identify.
