### ISSUE TITLE
Ask about license

### ISSUE THREAD

**Issue by kaocy** [indexeddbshim/IndexedDBShim#279]
Hi~I am a member of cdnjs, and I want to add this library.
I want to check if this library has two licenses, because there is only one license written in package.json.

https://github.com/cdnjs/cdnjs/issues/10261

**Comment by axemclion** [comment]
This does have 2 licenses. The package.json file says `license": "MIT OR Apache-2.0`. Looks like @brettz9 added it to package.json.

Here are the other relevant license discussions - https://github.com/axemclion/IndexedDBShim/issues?utf8=%E2%9C%93&q=is%3Aissue%20license

**Comment by brettz9** [comment]
I've pushed to `master` a change in `package.json` to reflect the license terms already agreed upon by the founders (as mentioned by @axemclion just now) and previously added as license files, i.e., `(MIT OR Apache-2.0)` (I just amended to include the parentheses which "should" be included).

Note that if you are considering using the project under `master` (which although it includes various improvements is still under a lot of development until our 3.0.0 release and may thus be less stable even while I try to keep `master` passing all previously passing tests or at least for the W3C tests), the number of `devDependencies` has grown, and although most are probably just for development, one would have to take a closer look to see the terms of code getting integrated into our packages builds.

Using [license-checker](https://www.npmjs.com/package/license-checker) and this long path (since it doesn't yet allow exclusions in a less repetitive manner) of exclusions of better-known permissive licenses, the results of lesser known licenses are showing the following (though there may even be fewer as I still need to prune my `node_modules` of no longer used modules): 

```bash
license-checker --exclude 'MIT, BSD, BSD*, ISC, MIT/X11, Apache-2.0, Apache 2, Apache 2.0, Unlicense, BSD-2-Clause, BSD-3-Clause, BSD-4-Clause, WTFPL, WTFPL OR MIT, MIT*, Public Domain, (MIT AND CC-BY-3.0), WTFPL OR ISC, BSD-like, CC-BY-4.0, (MIT OR Apache-2.0), (WTFPL OR MIT), (BSD-2-Clause OR MIT OR Apache-2.0), BSD-3-Clause OR MIT, MIT OR Apache-2.0'
```
├─ buffalo@0.1.3
│  ├─ licenses: UNKNOWN
│  ├─ repository: https://github.com/marcello3d/node-buffalo
│  ├─ publisher: Marcello Bastéa-Forte
│  ├─ email: marcello@cellosoft.com
│  ├─ url: http://marcello.cellosoft.com/
│  └─ licenseFile: C:\wamp\www\IndexedDBShim\node_modules\buffalo\LICENSE
├─ json-schema@0.2.3
│  ├─ licenses
│  │  ├─ 0: AFLv2.1
│  │  └─ 1: BSD
│  ├─ repository: https://github.com/kriszyp/json-schema
│  └─ publisher: Kris Zyp
├─ node-version@1.0.0
│  ├─ licenses: UNKNOWN
│  ├─ repository: https://github.com/srod/node-version
│  ├─ publisher: Rodolphe Stoclin
│  ├─ email: rodolphe@2clics.net
│  └─ url: http://2clics.net
├─ rx-lite@3.1.2
│  ├─ licenses: Apache License, Version 2.0
│  ├─ repository: https://github.com/Reactive-Extensions/RxJS
│  ├─ publisher: Cloud Programmability Team
│  └─ url: https://github.com/Reactive-Extensions/RxJS/blob/master/authors.txt
├─ stackframe@0.3.1
│  ├─ licenses: SEE LICENSE IN LICENSE
│  ├─ repository: https://github.com/stacktracejs/stackframe
│  └─ licenseFile: C:\wamp\www\IndexedDBShim\node_modules\stackframe\LICENSE
├─ tosource@0.1.1
│  ├─ licenses: UNKNOWN
│  ├─ repository: https://github.com/marcello3d/node-tosource
│  ├─ publisher: Marcello Bastéa-Forte
│  ├─ email: marcello@cellosoft.com
│  ├─ url: http://marcello.cellosoft.com/
│  └─ licenseFile: C:\wamp\www\IndexedDBShim\node_modules\tosource\LICENSE
├─ tweetnacl@0.14.3
│  ├─ licenses: SEE LICENSE IN COPYING.txt
│  ├─ repository: https://github.com/dchest/tweetnacl-js
│  ├─ publisher: TweetNaCl-js contributors
│  └─ licenseFile: C:\wamp\www\IndexedDBShim\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\request\node_modules\http-signature\node_modules\sshpk\node_modules\tweetnacl\COPYING.txt
└─ uglify-js@1.2.6
   ├─ licenses: UNKNOWN
   ├─ repository: https://github.com/mishoo/UglifyJS
   ├─ publisher: Mihai Bazon
   ├─ email: mihai.bazon@gmail.com
   └─ url: http://mihai.bazon.net/blog

I'd need to take a closer look to see which may have code getting included, but I think we are good with at least the most substantial portions...
