### ISSUE TITLE
Opening transaction for without a scope is possible

### ISSUE THREAD

**Issue by kristofdegrave** [indexeddbshim/IndexedDBShim#29]
If I use the shim I am able to open a transaction with an empty scope. Instead of returning an error for that, the transaction just gets created.

**Comment by axemclion** [comment]
Are you referring to code like `var transaction = db.transaction([], "readwrite")` ? 

I am looking at the specifiction here http://www.w3.org/TR/2012/WD-IndexedDB-20120524/#widl-IDBDatabase-transaction-IDBTransaction-any-storeNames-DOMString-mode and there is nothing about not passing an empty array. 

Is the expected behavior on passing empty array, to fail the transaction ?

**Comment by kristofdegrave** [comment]
Yes it is.

The objectstorenames argument isn't optional and must throw a InvalidAccessError when the  function was called with an empty list of store names

http://www.w3.org/TR/IndexedDB/#widl-IDBDatabase-transaction-IDBTransaction-any-storeNames-DOMString-mode

**Comment by JamesMessinger** [comment]
This issue has been fixed in the latest version.  Our parameter validation logic now matches native IndexedDB implementations in browsers.   Please give it a try and let us know if there are any problems.  Thanks!
