### ISSUE TITLE
6.0.1 -> 6.1.0 import error in Webpack build

### ISSUE THREAD

**Issue by booleanbetrayal** [indexeddbshim/IndexedDBShim#352]
Webpack builds break in 6.1.0 with the following error:

```
ERROR in ./node_modules/indexeddbshim/dist/indexeddbshim.min.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/back_royal/node_modules/indexeddbshim/dist'
resolve 'fs' in '/home/circleci/back_royal/node_modules/indexeddbshim/dist'
  Parsed request is a module
```

What am I missing here?

**Comment by brettz9** [comment]
Could you see if pointing to `master` solves it for you?

**Comment by booleanbetrayal** [comment]
`master` seems to work, but Webpack is throwing warnings now due to a dynamic `require()` statement breaking it's static import analysis:

```
WARNING in ./node_modules/indexeddbshim/dist/indexeddbshim.min.js 3:110968-110979
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/brent/Development/Pedago/back_royal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/brent/Development/Pedago/back_royal/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/brent/Development/Pedago/back_royal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/brent/Development/Pedago/back_royal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:22)
    at /Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compilation.js:1185:12
    at /Users/brent/Development/Pedago/back_royal/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./vendor/front-royal/modules/FrontRoyalStore/openDb.js
 @ ./vendor/front-royal/modules/FrontRoyalStore/FrontRoyalStore.js
 @ ./vendor/front-royal/modules/FrontRoyalStore/angularModule.js
 @ ./vendor/front-royal/components/lessons/scripts/lessons_module.js
 @ ./vendor/front-royal/components sync ^(?!.*admin\/|.*editor\/|.*reports\/|.*spec\/|.*content_item_editor\/).*_module\.js$
 @ ./vendor/front-royal/deps.js
 @ ./vendor/front-royal/deps.dev.js
```

**Comment by brettz9** [comment]
Ok, I think I have a fix for this in my personal `master` branch (as well as adding nyc testing coverage and moving from Qunit tests to Mocha). I've just avoiding doing all of the requiring except in our Node files, relying on them to auto-set a config property (`CFG.fs`) which the `IDBFactory` will call if present (but not do any requiring there). This should also work for #313.

Let me know if `master` for https://github.com/brettz9/IndexedDBShim works for you, and then I can publish a release (though as per #353 , it might be under a new umbrella if I don't hear back from axemclion). Thanks!

**Comment by booleanbetrayal** [comment]
Seeing it work in `master` of your fork now, @brettz9 . Thanks!

**Comment by booleanbetrayal** [comment]
Going to re-open until this actually gets fixed upstream (@brettz9 / @axemclion)

**Comment by brettz9** [comment]
As @axemclion hasn't responded after a number of attempts, I have created an "indexeddbshim" organization (while inviting him to it): https://www.npmjs.com/package/@indexeddbshim/indexeddbshim

He had said a while back that I might maintain on my own anyways, so I figure this is a natural course.

It's on github at https://github.com/indexeddbshim/indexeddbshim

And we now have our demo files on the more stable Github Pages: https://indexeddbshim.github.io/indexeddbshim/

I haven't kicked the tires enough everywhere to find out if anything else needs updating, so reports at https://github.com/indexeddbshim/indexeddbshim/issues would be welcome.

And I've filed https://github.com/cdnjs/cdnjs/issues/13757 to try to get our own cdnjs copy for the new package.

I'm hesitant to close issues others have filed here such as this one on my own now since I'm now planning to maintain over there instead (though feel free to close the issue yourself if you wish). I do intend to inform users here of any fixes on the existing issues here (at least until we may hear back from @axemclion).

**Comment by brettz9** [comment]
@axemclion has gotten things all nicely set up, redirecting to the `indexeddbshim/indexeddbshim` organization, and I've ported my fork changes to it, deprecated the separate `@indexeddbshim/indexeddbshim` npm package I had released, and released the fork changes as part of the regular `indexeddbshim` package (release 6.6.0). So I will close the issue since it should be fixed in this main project as well. Feel free to report back if there are any issues.
