### ISSUE TITLE
Transaction is inactivated while still in progress when used with IDB.

### ISSUE THREAD

**Issue by wishawa** [indexeddbshim/IndexedDBShim#361]
I'm trying to use [IDB](https://github.com/jakearchibald/idb) on top of this library in an environment where only WebSQL is available (React Native and SQLite).

When calling `cursor.continue()`, `DOMException: A request was placed against a transaction which is currently not active, or which is finished` is thrown.

The error does not happen if I use IDB in with normal LocalStorage in both Firefox and Chrome.

I've created a demo [here](https://lf21w.csb.app/), with source code [here](https://codesandbox.io/s/cocky-ardinghelli-lf21w?file=/src/index.js). (`shimIndexedDB.__useShim();` is used to simulate the environment, so you probably need Chrome for this demo to work).

**Comment by wishawa** [comment]
Apologies. I did not read https://github.com/indexeddbshim/IndexedDBShim#taskmicro-task-timing.
Seems like this is a known issue. Closing.

**Comment by nbrustein** [comment]
I wanted to add a note on here because https://github.com/indexeddbshim/IndexedDBShim#taskmicro-task-timing did not suggest any sort of workaround to the problem, but I think I found a workaround at least in my case.

When I had code like this, I ran into the "inactive transaction" issue (this is simplified pseudo-code. It doesn't demonstrate exactly what I was trying to do):

```
await db.transaction('rw', db.myTable, async () => {
    const someResult = await db.myTable.toArray();
    
    return db.myTable.bulkPut(someResult.map(row => {
        // some modificaiton
    }));
});
```

When I refactored it like this, the problem went away:

```
await db.transaction('rw', db.myTable, () => {
    return await db.myTable.toArray().then(someResult => {
        return db.myTable.bulkPut(someResult.map(row => {
            // some modificaiton
        }));
    });
});
```

Apparently, switching from an `async` function to `then` got rid of the tick that was causing an issue. TBH, I don't understand this. It doesn't make sense with the way I thought aysnc functions worked, but it did seem to fix my problem.

It might make sense to add this in as a suggested workaround in the docs at https://github.com/indexeddbshim/IndexedDBShim#taskmicro-task-timing

**Comment by dfahlander** [comment]
It's impossible for the shim to automatically commit a transaction after the promise loop is done. That used to be an issue in browsers historically also that Dexie was the first library to overcome by implementing its own promise with its own microtask queue (See https://github.com/dexie/Dexie.js/issues/317). Since then, browsers fixed this issue and IndexedDB plays well with promises, but application-level code does not have access to the event when a micro-task queue is done. The reason your workaround works is that it's using dexie's workaround for this historical limitation that still exists in IndexedDBShim. Another workaround is to transpile async / await. Either transpile to target ES2016, or use babel with `@babel/plugin-transform-async-to-generator` plugin only. It will let other fancy features be but only transpile async/await. An example babel config for this can be found in this github comment: https://github.com/dexie/Dexie.js/issues/2005#issuecomment-2355187615 - it's about another issue where dexie's await-support conflicts with zonejs but the solution is the same.

**Comment by nbrustein** [comment]
> It's impossible for the shim to automatically commit a transaction after the promise loop is done. That used to be an issue in browsers historically also that Dexie was the first library to overcome by implementing its own promise with its own microtask queue (See [dexie/Dexie.js#317](https://github.com/dexie/Dexie.js/issues/317)). Since then, browsers fixed this issue and IndexedDB plays well with promises, but application-level code does not have access to the event when a micro-task queue is done. The reason your workaround works is that it's using dexie's workaround for this historical limitation that still exists in IndexedDBShim. Another workaround is to transpile async / await. Either transpile to target ES2016, or use babel with `@babel/plugin-transform-async-to-generator` plugin only. It will let other fancy features be but only transpile async/await. An example babel config for this can be found in this github comment: [dexie/Dexie.js#2005 (comment)](https://github.com/dexie/Dexie.js/issues/2005#issuecomment-2355187615) - it's about another issue where dexie's await-support conflicts with zonejs but the solution is the same.

Yeah, I know about the transpiling fix because this issue actually turned up for us when we stopped transpiling for es5. Thanks for the comments.
