### ISSUE TITLE
Deleting Indexes 

### ISSUE THREAD

**Issue by axemclion** [indexeddbshim/IndexedDBShim#4]
Deleting Indexes does not delete index columns

**Comment by JamesMessinger** [comment]
This is fixed now.  (as of v1.0.3)

The column can't actually be deleted, because WebSql doesn't support `DROP COLUMN`.  So instead, we just add a `__deleted` flag to the index, and we ignore any indexes with that flag.  If another index is added later with the same name, then the existing column is used and the `__deleted` flag is set to `false`.
