### ISSUE TITLE
What is the best way to search the local data set using the adapter?

### ISSUE THREAD

**Issue by JesseEdwardThompson** [indexeddbshim/IndexedDBShim#75]
I am building an application for customer service account management. The way in which I use IndexedDB is to fetch and maintain local account metadata to expedite searching and browsing about three thousand such accounts. I want to support Safari if possible, and have used the adapter successfully as a patch. However, my search algorithm is terrifically slow when the adapter kicks in. I have configured indexes for each field that is being searched and use a cursor to loop through the data to look for substring matches. What can I do to increase performance? Do you have a recommended method?

**Comment by axemclion** [comment]
Unfortunately, the way that indexes are created here are pretty inefficient for the sake of following the specification. The indexes sort of do twice the lookup. What does your search algorithm do ?

**Comment by JesseEdwardThompson** [comment]
Simplifying somewhat, I set up a cursor on each index and then loop through the values and use a regular expression to strip out everything except alphanumeric and then look for the query as a substring. 

``` js
var results = connection.transaction("accounts").objectStore("accounts").index("phone").openCursor();

results.onsucccess = function(e)
{
    var cursor = e.target.result;

    if (cursor)
    {
        // Look for substring
        if (cursor.key.replace(/[^a-zA-Z0-9]+/, '').toLowerCase().indexOf(query) != -1)
            Callback(match);

        cursor.continue(); 
    }
}
```

Would you suggest that I setup a cursor on the objectStore itself and avoid indexes then? Or take some other approach?

**Comment by brettz9** [comment]
I'm not sure this question belongs here, especially since there may not be one perfect answer. Feel free to report back though if you do find your own optimal solution or file an issue/PR if you find a way to optimize our code internally.

You might also try asking on StackOverflow (or Programmers StackExchange) with the `indexeddbshim` , `indexeddb`, and/or `optimization` tags, especially if you can describe a number of possible strategies you've considered. Best wishes...
